### ISSUE TITLE
Configure whether tests are run on same machine as web server

### ISSUE THREAD

**Issue by agold2** [tanarurkerem/DrupalExtensionStarterKit#1]
Excited about this kit as it looks like it greatly simplifies installation.

I cloned it outside of a Drupal installation, so when running bin/behat -dl I received the error:

  [Drupal\Exception\BootstrapException]  
  Unable to determine Drupal core version. Supported versions are 6, 7, and 8.  

I got through the error in two different ways: 1) by disabling the Drupal API driver in behat.yml and 2) by moving the starter kit into /sites/all/modules/custom/my_module/ 

Sometimes I would like to run tests on remote machines so would be nice to configure this by script.

What do you think about having the setenvironment.sh script prompt "Will tests be run on same machine as the web server?" If on same machine, use Drupal API driver and prompt for absolute path to Drupal root, otherwise disable Drupal API driver and don't prompt for Drupal root? 

I may be able to contribute a patch.

**Comment by tanarurkerem** [comment]
Thanks for your review! (You are the first :) )
It is sound good for me. I wait your patch.
