### ISSUE TITLE
Error when running bin/behat

### ISSUE THREAD

**Issue by heatherpriceonline** [tanarurkerem/DrupalExtensionStarterKit#5]
I get this Error when I try to run bin/behat.
`[Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]
  'Behat\MinkExtension\Extension' extension file or class could not be located.`

Did I install incorrectly? The file doesn't look like it is there.

**Comment by tanarurkerem** [comment]
The Drupal Extension changed. I corrected this issue, please try again.
