### ISSUE TITLE
Selenium not being downloaded

### ISSUE THREAD

**Issue by eliza411** [tanarurkerem/DrupalExtensionStarterKit#6]
I was trying this out in response to https://www.drupal.org/node/2185971 on Ubuntu 14.04.

I ran into a few issues, the first of which was: 

```
curl: Remote file name has no length!
curl: try 'curl --help' or 'curl --manual' for more information 
mv: cannot stat ‘selenium-server-*’: No such file or directory
```

curl version:  7.35.0

**Comment by tanarurkerem** [comment]
@eliza411 Thank's for your work. I refactor download process, and use an XML instead of HTML file list. I hope this will be good in the future.
