### ISSUE TITLE
Noise from sed looking for .bak files

### ISSUE THREAD

**Issue by eliza411** [tanarurkerem/DrupalExtensionStarterKit#7]
The next issue I ran into:

```
$ bash setenviroment.sh
```

   Your Base URL (default: http://drupal.loc/): http://seven.l
    sed: can't read .bak: No such file or directory
    rm: cannot remove ‘behat.yml.bak’: No such file or directory
    Run tests from webserver and use Drupal API driver? (y/n):y
    sed: can't read .bak: No such file or directory
    sed: can't read .bak: No such file or directory
    sed: can't read .bak: No such file or directory

It's possible to complete the setup. They're just like to prove disconcerting

**Comment by tanarurkerem** [comment]
hmm.. it is looking for a permission issue.
Is this directory writeable?

**Comment by eliza411** [comment]
You're asking about the permissions for the directory containing the StarterKit into, correct? It's owned by me and perms are 775 (as are the permissions of the webroot I'm using.)

drwxrwxr-x 6 melissa melissa    4096 Dec 13 13:41 .

**Comment by tanarurkerem** [comment]
hmm.. Which operating system do you use? I work and test on OS X Leopard.

I modified "sed -i .bak" to "sed -i'.bak'". It is working for me, and hope It will be good for you, and everybody.

Please try.

The man pages:
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/sed.1.html
https://www.gnu.org/software/sed/manual/sed.html

And the stackoverflow thread which I found in this topic:
http://stackoverflow.com/questions/7733922/sed-command-creates-randomly-named-files

**Comment by eliza411** [comment]
That appears to have done the trick.

I use Ubuntu 14.04
