### ISSUE TITLE
Test feature returns undefined steps

### ISSUE THREAD

**Issue by eliza411** [tanarurkerem/DrupalExtensionStarterKit#8]
When I run bin/behat, 

```
Scenario: Access homepage    # features/testEnviromentWorks.feature:3
  When I go to homepage
  Then the response status code should be 200

1 scenario (1 undefined)
2 steps (2 undefined)
0m0.18s (33.24Mb)

--- Snippets for the following steps in the default suite were not generated (check your configuration):

  When I go to homepage
  Then the response status code should be 200
```

This is probably because contexts have been split up but not added to the behat.yml. See https://behat-drupal-extension.readthedocs.org/en/master/localinstall.html (Note, I've done a big docs cleanup that hasn't been merged yet, so while the example of adding the contexts is accurate, there are a lot of details in the docs that aren't necessarily up-to-date.)

I initially pasted the wrong output. I corrected that.

**Comment by tanarurkerem** [comment]
@eliza411 Thanks. I corrected it.
